Repository apache/camel-k, pull requests merged in 2020-10, with the labels that each got.

#1751 Fix #1750: auto-compress/encode binary sources and resources
  pkg/cmd/modeline.go
  pkg/cmd/run.go
Labels: kind/bug

#1780 Fix #1778: allow pushing to broker via KameletBinding
  e2e/yaks/common/kamelet-binding-broker/kamelet.feature
  e2e/yaks/common/kamelet-binding-broker/logger-sink-binding.yaml
  e2e/yaks/common/kamelet-binding-broker/logger-sink.kamelet.yaml
  e2e/yaks/common/kamelet-binding-broker/timer-source-binding.yaml
  e2e/yaks/common/kamelet-binding-broker/timer-source.kamelet.yaml
  e2e/yaks/common/kamelet-binding-broker/yaks-config.yaml
  pkg/util/bindings/knative_ref.go
  pkg/util/knative/apis_test.go
  pkg/util/knative/knative.go
  pkg/util/knative/uri.go
  pkg/util/knative/uri_test.go
Labels: backport release-1.2.x, kind/bug

#1786 Fix #1785: propagate klb changes to integrations
  e2e/knative/files/display.groovy
  e2e/knative/kamelet_test.go
  e2e/support/test_support.go
  pkg/cmd/reset.go
  pkg/controller/kameletbinding/common.go
  pkg/controller/kameletbinding/initialize.go
  pkg/controller/kameletbinding/kamelet_binding_controller.go
  pkg/controller/kameletbinding/monitor.go
Labels: backport release-1.2.x

#1796 Fixes ENTESB-15219: only use default values when user doesn't provide a kamelet property value in integration
  pkg/trait/kamelets.go
Labels: kind/bug
