Repository apache/camel-k, pull requests merged in 2020-06, with the labels that each got.

#1491 support for jitpack dependencies
  pkg/builder/builder_steps.go
  pkg/util/jitpack/jitpack.go
  pkg/util/jitpack/jitpack_test.go
Labels: kind/feature

#1490 feat: Prometheus support for Quarkus based on MicroProfile Metrics
  deploy/traits.yaml
  docs/modules/traits/pages/prometheus.adoc
  pkg/trait/prometheus.go
  pkg/trait/prometheus_test.go
Labels: kind/feature

#1527 #1524 set the OLM channel used on install to 'stable'
  pkg/util/olm/operator.go
Labels: backport release-1.0.x

#1540 Cannot expose knative endpoints in YAML
  deploy/resources.go
  e2e/knative/files/flow.yaml
  e2e/knative/knative_test.go
  pkg/trait/knative.go
  pkg/trait/service_test.go
Labels: backport release-1.0.x

#1558 fix(jvm): Integration do not shutdown gracefully when jvm.print-command is set
  pkg/trait/jvm.go
Labels: backport release-1.0.x, kind/bug

#1553 fix: bug in utility function
  pkg/util/util.go
Labels: backport release-1.0.x, kind/bug

#1564 fix typo
  release.adoc
Labels: backport release-1.0.x
