Repository apache/camel-k, pull requests merged in 2021-03, with the labels that each got.

#2124 fix: only assume secure pull if the main registry and the base image registry are different
  pkg/builder/spectrum/publisher.go
Labels: kind/bug

#2143 doc: added documentation about deploying Camel K on k3s
  docs/modules/ROOT/pages/installation/installation.adoc
  docs/modules/ROOT/pages/installation/k3s.adoc
  docs/modules/ROOT/pages/installation/registry/k3s.adoc
Labels: area/documentation

#2148 Fix #2035: invalid YAML should not make the operator panic
  pkg/util/source/inspector_yaml.go
  pkg/util/source/inspector_yaml_test.go
Labels: backport release-1.3.x, kind/bug
