Repository apache/camel-k, pull requests merged in 2021-05, with the labels that each got.

#2301 chore(cli): Update CRDs when force installing cluster resources
  pkg/cmd/install.go
  pkg/install/cluster.go
Labels: area/cli

#2304 chore(ci): Cancel running workflows when PRs are updated
  .github/workflows/build.yml
  .github/workflows/builder.yml
  .github/workflows/knative.yml
  .github/workflows/kubernetes.yml
  .github/workflows/local.yml
  .github/workflows/openshift.yml
  .github/workflows/upgrade.yml
  .github/workflows/validate.yml
Labels: area/continuous integration

#2251 fix(ci): Upgrade Kubernetes to version 1.21.1
  .github/workflows/builder.yml
  .github/workflows/knative.yml
  .github/workflows/kubernetes.yml
  .github/workflows/upgrade.yml
Labels: area/continuous integration

#2310 chore(ci): Use `github.ref` instead of `github.head_ref` as concurrency group key
  .github/workflows/build.yml
  .github/workflows/builder.yml
  .github/workflows/knative.yml
  .github/workflows/kubernetes.yml
  .github/workflows/local.yml
  .github/workflows/openshift.yml
  .github/workflows/upgrade.yml
  .github/workflows/validate.yml
Labels: area/continuous integration

#2308 Fix #2237: add flag to disable installation of default kamelets
  pkg/controller/integrationplatform/create.go
  pkg/install/optional.go
  pkg/util/defaults/defaults.go
  pkg/util/defaults/defaults_support.go
  pkg/util/defaults/defaults_test.go
  script/Makefile
Labels: backport release-1.4.x
