Repository apache/camel-k, pull requests merged in 2021-10, with the labels that each got.

#2668 chore: Parallel Kamelets reconciliation
  pkg/controller/kamelet/kamelet_controller.go
Labels: area/kamelets

#2664 chore : automatic PR creation to update "peripheral" go dependencies
  .github/dependabot.yml
Labels: area/continuous integration

#2666 fix: Affinity trait must run after the Knative Service trait
  pkg/trait/affinity.go
Labels: kind/bug, area/knative

#2670 fix: Handle Integration changes while waiting for Kit build
  pkg/controller/integration/build_kit.go
Labels: kind/bug

#2667 feat(native): Add support for Knative service gradual roll-out
  docs/modules/traits/pages/knative-service.adoc
  pkg/resources/resources.go
  pkg/trait/knative_service.go
  pkg/trait/knative_service_test.go
  resources/traits.yaml
Labels: kind/feature, area/knative

#2677 feat: Add progress-deadline-seconds option to deployment trait
  docs/modules/traits/pages/deployment.adoc
  pkg/resources/resources.go
  pkg/trait/deployment.go
  pkg/trait/deployment_test.go
  resources/traits.yaml
Labels: kind/feature

#2676 fix(cli): kamel install fails with error: Object 'Kind' is missing in 'null'
  pkg/install/operator.go
Labels: area/installation
