Repository apache/camel-k, pull requests merged in 2021-06, with the labels that each got.

#2362 chore(doc): Update high-level architecture diagram
  docs/modules/ROOT/assets/images/architecture/camel-k-high-level.svg
  docs/modules/ROOT/pages/architecture/architecture.adoc
Labels: area/documentation

#2386 chore(doc): Add autoscaling with Knative documentation
  docs/modules/ROOT/pages/scaling/integration.adoc
Labels: area/documentation

#2398 chore(build): Cancel s2i Build on context cancellation or timeout
  pkg/builder/s2i.go
Labels: area/build-system

#2402 fix(e2e): Remove image pull secret e2e test race conditions
  e2e/common/traits/pull_secret_test.go
Labels: area/continuous integration

#2401 chore: Upgrade controller-runtime to v0.8.3
  go.mod
  go.sum
Labels: area/core, status/wip

#2433 doc: readme cleanup
  README.adoc
Labels: area/documentation

#2292 fix(integration) Integration not marked as Failed when Camel is unabl…
  .gitignore
  e2e/common/files/BadRoute.java
  e2e/common/integration_fail_test.go
  pkg/controller/integration/error.go
  pkg/controller/integration/monitor.go
  pkg/util/kubernetes/client.go
  pkg/util/kubernetes/conditions.go
Labels: area/core

#2442 Fix #2441: parse parameters in YAML DSL
  e2e/common/cron_test.go
  e2e/common/files/cron-yaml.yaml
  pkg/util/source/inspector_yaml.go
  pkg/util/source/inspector_yaml_test.go
Labels: kind/bug
