Repository apache/camel-k, pull requests merged in 2021-08, with the labels that each got.

#2545 fix(builder): Fix race-condition when Build transitions to running phase
  pkg/controller/build/monitor_routine.go
Labels: backport release-1.5.x

#2547 fix: Fix cross-namespace creator resource events
  pkg/controller/integration/build_kit.go
  pkg/event/manager.go
  pkg/trait/container.go
  pkg/util/kubernetes/camel.go
Labels: backport release-1.5.x

#2568 [Backport] fix(api): property leading space
  pkg/apis/camel/v1/integration_types_support.go
  pkg/apis/camel/v1/integration_types_support_test.go
Labels: backport release-1.5.x

#2544 (backport) Forcelly set QUARKUS_LOG_CONSOLE_JSON to false if the trait is not provided (GH issue #2539)
  pkg/trait/logging.go
  pkg/trait/trait_types.go
Labels: kind/bug, backport release-1.5.x

#2595 chore(strimzi): upgrade API to v1beta2
  addons/strimzi/addtoscheme_strimzi_duck_v1beta2.go
  addons/strimzi/duck/client/internalclientset/clientset.go
  addons/strimzi/duck/client/internalclientset/doc.go
  addons/strimzi/duck/client/internalclientset/fake/clientset_generated.go
  addons/strimzi/duck/client/internalclientset/fake/doc.go
  addons/strimzi/duck/client/internalclientset/fake/register.go
  addons/strimzi/duck/client/internalclientset/scheme/doc.go
  addons/strimzi/duck/client/internalclientset/scheme/register.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/doc.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/duck_client.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/fake/doc.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/fake/fake_duck_client.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/fake/fake_kafka.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/fake/fake_kafkatopic.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/generated_expansion.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/kafka.go
  addons/strimzi/duck/client/internalclientset/typed/duck/v1beta2/kafkatopic.go
  addons/strimzi/duck/v1beta2/doc.go
  addons/strimzi/duck/v1beta2/duck_types.go
  addons/strimzi/duck/v1beta2/register.go
  addons/strimzi/duck/v1beta2/zz_generated.deepcopy.go
  addons/strimzi/strimzi.go
  addons/strimzi/strimzi_test.go
  pkg/resources/resources.go
  script/gen_client_strimzi.sh
Labels: kind/feature
