Repository apache/camel-k, pull requests merged in 2021-02, with the labels that each got.

#1971 Test PR do not merge
  README.adoc
Labels: backport release-1.3.x

#1987 Fix #1986: use properties instead of URL encoding for Kamelets in bin…
  pkg/controller/kameletbinding/common.go
  pkg/util/bindings/api.go
  pkg/util/bindings/bindings_test.go
  pkg/util/bindings/kamelet.go
  script/gen_release_notes.sh
Labels: backport release-1.3.x, kind/bug

#1989 Fix a little typo good for testing backport action
  README.adoc
Labels: backport release-1.3.x

#1985 fix(OLM): Add missing internal-objects annotation to Kustomize base CSV manifest
  config/manifests/bases/camel-k.clusterserviceversion.yaml
Labels: area/olm

#1993 Fix #1992: allow accessing Strimzi "kafkatopics" instead of "topics"
  config/rbac/operator-role-olm.yaml
  config/rbac/operator-role-strimzi.yaml
  deploy/operator-role-olm.yaml
  deploy/operator-role-strimzi.yaml
  helm/camel-k/templates/operator-role.yaml
Labels: backport release-1.3.x, kind/bug

#1991 fix(OLM): Remove replaces field from Kustomize base CSV manifest
  config/manifests/bases/camel-k.clusterserviceversion.yaml
Labels: area/olm

#1996 Picky commit for testing backport action
  README.adoc
Labels: backport release-1.3.x

#2001 Document OLM based deployment from source
  docs/modules/ROOT/nav-end.adoc
  docs/modules/ROOT/pages/contributing/local-deployment-olm.adoc
Labels: area/documentation, area/olm
