Repository apache/camel-k, pull requests merged in 2021-11, with the labels that each got.

#2740 feat: Health trait
  docs/modules/ROOT/nav.adoc
  docs/modules/traits/pages/container.adoc
  docs/modules/traits/pages/health.adoc
  e2e/knative/knative_platform_test.go
  pkg/resources/resources.go
  pkg/trait/container.go
  pkg/trait/container_probes_test.go
  pkg/trait/container_test.go
  pkg/trait/health.go
  pkg/trait/jolokia.go
  pkg/trait/jvm.go
  pkg/trait/jvm_test.go
  pkg/trait/knative_service.go
  pkg/trait/prometheus.go
  pkg/trait/quarkus.go
  pkg/trait/trait_register.go
  pkg/trait/trait_types.go
  resources/traits.yaml
Labels: kind/feature

#2757 chore(doc): Add 1.7.x documentation
  docs/antora.yml
Labels: area/documentation

#2754 Fix #2638: fix condition for external kit and add test
  e2e/common/scale_integration_test.go
  pkg/trait/container.go
Labels: backport release-1.7.x
