Repository apache/camel-k, pull requests merged in 2022-11, with the labels that each got.

#3786 feat(build): parse cmd execution for errors
  pkg/util/command.go
  pkg/util/command_test.go
  pkg/util/jvm/keystore.go
  pkg/util/maven/maven_log.go
  pkg/util/maven/maven_log_test.go
Labels: kind/feature

#3809 Minor steps improvements in release guide
  release.adoc
Labels: backport release-1.10.x

#3834 fix(GC): Default to APIResourceList group when APIResource group is empty
  pkg/trait/gc.go
Labels: kind/bug

#3828 chore(test) : TestRunAndLog to pass on mac os
  pkg/util/command_test.go
Labels: kind/bug
