Repository apache/camel-k, pull requests merged in 2022-02, with the labels that each got.

#2967 fix(cli): Kamel CLI zero-code exists when trait properties validation fails (1.8.x backport)
  pkg/cmd/run.go
Labels: kind/bug

#2986 fix(cli): kamel run -v should configure the mount trait
  config/crd/bases/camel.apache.org_integrations.yaml
  config/crd/bases/camel.apache.org_kameletbindings.yaml
  helm/camel-k/crds/crd-integration.yaml
  helm/camel-k/crds/crd-kamelet-binding.yaml
  pkg/apis/camel/v1/integration_types.go
  pkg/cmd/run.go
  pkg/resources/resources.go
Labels: kind/bug

#2991 fix(cli): kamel run -v should configure the mount trait (1.8.x backport)
  config/crd/bases/camel.apache.org_integrations.yaml
  config/crd/bases/camel.apache.org_kameletbindings.yaml
  helm/camel-k/crds/crd-integration.yaml
  helm/camel-k/crds/crd-kamelet-binding.yaml
  pkg/apis/camel/v1/integration_types.go
  pkg/cmd/run.go
  pkg/resources/resources.go
Labels: kind/bug

#2999 fix(cmd/run): allow multiple resources
  docs/modules/ROOT/pages/configuration/runtime-resources.adoc
  e2e/common/config/config_test.go
  e2e/common/config/files/resource-configmap-key-location-route.groovy
  examples/user-config/resource-configmap-key-location-route.groovy
  pkg/trait/mount.go
  pkg/util/resource/config.go
Labels: backport release-1.8.x

#3045 Release note script: Check if the GITHUB_TOKEN var has been set befor…
  release.adoc
  script/gen_release_notes.sh
Labels: backport release-1.6.x, backport release-1.7.x, backport release-1.8.x

#3048 Makefile Release staging: Pass the remote repository name as argument…
  script/Makefile
Labels: backport release-1.6.x, backport release-1.7.x, backport release-1.8.x
