Repository apache/camel-k, pull requests merged in 2022-03, with the labels that each got.

#3056 fix: The error handler trait should update status dependencies
  pkg/trait/error_handler.go
  pkg/trait/error_handler_test.go
Labels: backport release-1.8.x

#3073 Release documentation: Update docs for OperatorHub with new repositories
  release.adoc
Labels: backport release-1.6.x, backport release-1.7.x, backport release-1.8.x

#3108 fix: Propagate readiness condition message in KameletBinding if present
  e2e/knative/kamelet_test.go
  pkg/controller/kameletbinding/monitor.go
Labels: kind/bug

#3114 fix: Propagate readiness condition message in KameletBinding if present (1.8.x backport)
  e2e/knative/kamelet_test.go
  pkg/controller/kameletbinding/monitor.go
Labels: kind/bug
