Repository apache/camel-k, pull requests merged in 2022-09, with the labels that each got.

#3594 feat(ci): smoke test before nightly release
  .github/workflows/release-workflow.yml
Labels: kind/feature

#3558 feat(cli): Allow to specify custom Kaniko and Buildah images
  config/crd/bases/camel.apache.org_builds.yaml
  docs/modules/ROOT/partials/apis/camel-k-crds.adoc
  helm/camel-k/crds/crd-build.yaml
  pkg/apis/camel/v1/build_types.go
  pkg/apis/camel/v1/integrationplatform_types_support.go
  pkg/builder/buildah.go
  pkg/builder/kaniko.go
  pkg/cmd/install.go
  pkg/cmd/install_test.go
  pkg/controller/build/build_pod.go
  pkg/controller/integrationplatform/kaniko_cache.go
  pkg/resources/resources.go
  pkg/trait/builder.go
Labels: kind/feature, builder/buildah, builder/kaniko

#3589 feat(cli): Add tail flag to the log command
  e2e/namespace/install/cli/log_test.go
  pkg/cmd/debug.go
  pkg/cmd/log.go
  pkg/cmd/run.go
  pkg/util/kubernetes/log/annotation_scraper.go
  pkg/util/kubernetes/log/pod_scraper.go
  pkg/util/kubernetes/log/util.go
Labels: kind/feature

#3610 fix: Panic with odd number of key / value arguments
  pkg/util/camel/camel_util.go
Labels: kind/bug

#3626 feat(cmd/run): secret/configmap as runtime/build-time properties
  docs/modules/ROOT/pages/configuration/build-time-properties.adoc
  docs/modules/ROOT/pages/configuration/runtime-properties.adoc
  e2e/global/common/config/config_test.go
  pkg/cmd/run.go
  pkg/cmd/run_help.go
  pkg/cmd/run_help_test.go
  pkg/cmd/run_test.go
Labels: kind/feature

#3652 trait(ingress): Configure backend in ingress rule
  pkg/trait/ingress.go
  pkg/trait/ingress_test.go
Labels: kind/feature

#3682 fix(#3671): Fix native mode for KameletBinding
  pkg/trait/quarkus.go
  pkg/trait/quarkus_test.go
Labels: kind/bug

#3691 fix: Use SIGTERM and SIGINT aware context for bootstrap operations
  pkg/cmd/operator/operator.go
Labels: kind/bug
