Repository apache/camel-k, pull requests merged in 2022-07, with the labels that each got.

#3444 fix(cli): `kamel local build` doesn't support same dependency notation
  e2e/local/files/dependency.groovy
  e2e/local/local_build_test.go
  e2e/local/local_run_test.go
  pkg/apis/camel/v1/integration_types_support.go
  pkg/apis/camel/v1/integration_types_support_test.go
  pkg/cmd/local.go
  pkg/cmd/local_build.go
  pkg/cmd/local_build_test.go
  pkg/cmd/local_inspect.go
  pkg/cmd/local_inspect_test.go
  pkg/cmd/local_run.go
  pkg/cmd/local_run_test.go
  pkg/cmd/local_util.go
  pkg/cmd/local_util_test.go
  pkg/cmd/root.go
  pkg/cmd/run.go
  pkg/util/camel/camel_dependencies.go
Labels: kind/bug, area/cli

#3477 chore(knative): upgrade Knative to 1.3 (0.30) #3381
  .github/actions/kamel-install-knative/install-knative.sh
  go.mod
  go.sum
Labels: kind/feature

#3488 fix(ci): build before making images
  script/Makefile
Labels: kind/bug
