Repository apache/camel-k, pull requests merged in 2022-01, with the labels that each got.

#2917 Updated the helm index.yml file, by only adding the latest helm chart
  docs/charts/index.yaml
Labels: backport main

#2929 fix: Camel Catalog generation fails with empty Maven effective settings
  pkg/util/camel/catalog.go
Labels: kind/bug

#2904 fix(e2e): Use X.Y channels for OLM upgrade e2e tests (1.6.x backport)
  .github/workflows/upgrade.yml
  e2e/upgrade/olm_upgrade_test.go
Labels: kind/bug

#2936 fix: Camel Catalog generation fails with empty Maven effective settings (1.8.x backport)
  pkg/util/camel/catalog.go
Labels: kind/bug

#2953 fix(api): Add missing loader metadata field in CamelCatalog API
  config/crd/bases/camel.apache.org_camelcatalogs.yaml
  helm/camel-k/crds/crd-camel-catalog.yaml
  pkg/apis/camel/v1/camelcatalog_types.go
  pkg/resources/resources.go
Labels: kind/bug

#2964 fix(cli): Kamel CLI zero-code exists when trait properties validation fails
  pkg/cmd/run.go
Labels: kind/bug, area/cli, backport release-1.8.x
