Repository apache/camel-k, pull requests merged in 2022-10, with the labels that each got.

#3711 chore: Upgrade go.uber.org/automaxprocs to v1.5.1
  go.mod
  go.sum
Labels: kind/bug

#3684 Adds the default maven repositories if extra ones are added
  pkg/cmd/install.go
Labels: kind/bug

#3721 chore: Upgrade go.uber.org/automaxprocs to v1.5.1
  go.mod
  go.sum
Labels: kind/bug

#3723 fix(cli): don't verify operator
  pkg/cmd/bind.go
  pkg/cmd/run.go
Labels: kind/bug

#3724 [backport] fix(cli): don't verify operator
  pkg/cmd/bind.go
  pkg/cmd/run.go
Labels: kind/bug

#3732 Fixes licenses in pkg
  pkg/install/kamelets.go
  pkg/install/platform.go
Labels: backport release-1.10.x

#3423 Minor updates for bundle generation
  config/manifests/bases/camel-k.clusterserviceversion.yaml
  script/Makefile
Labels: status/never-stale

#3783 feat(controller): add Ready condition to IntegrationPlatform
  e2e/namespace/install/cli/install_test.go
  e2e/support/test_support.go
  pkg/apis/camel/v1/integrationplatform_types.go
  pkg/apis/camel/v1/integrationplatform_types_support.go
  pkg/controller/integrationplatform/create.go
  pkg/controller/integrationplatform/monitor.go
Labels: kind/feature
