Repository apache/camel-k, pull requests merged in 2023-07, with the labels that each got.

#4527 fix(ci): proper arch label
  script/cross_compile.sh
Labels: kind/bug

#4529 fix(ctrl): dynamic builder registry organization
  pkg/controller/catalog/initialize.go
Labels: kind/bug

#4533 fix(e2e): increase trait test timeout
  script/Makefile
Labels: kind/bug

#4549 Fix Unable to retrieve CamelCatalog with global installation
  pkg/cmd/version.go
Labels: kind/bug

#4564 chore(deps): spectrum 6.0.28
  go.mod
  go.sum
Labels: dependencies

#4567 fix(cli): skip k8s lookup when dry-run
  pkg/cmd/run.go
Labels: kind/bug

#4568 feat(trait): Add maven profile to Integration in builder trait
  config/crd/bases/camel.apache.org_builds.yaml
  config/crd/bases/camel.apache.org_integrationkits.yaml
  config/crd/bases/camel.apache.org_integrationplatforms.yaml
  config/crd/bases/camel.apache.org_integrations.yaml
  config/crd/bases/camel.apache.org_kameletbindings.yaml
  config/crd/bases/camel.apache.org_pipes.yaml
  docs/modules/ROOT/partials/apis/camel-k-crds.adoc
  docs/modules/traits/pages/builder.adoc
  e2e/common/traits/builder_test.go
  helm/camel-k/crds/crd-build.yaml
  helm/camel-k/crds/crd-integration-kit.yaml
  helm/camel-k/crds/crd-integration-platform.yaml
  helm/camel-k/crds/crd-integration.yaml
  helm/camel-k/crds/crd-kamelet-binding.yaml
  helm/camel-k/crds/crd-pipe.yaml
  pkg/apis/camel/v1/common_types_support.go
  pkg/apis/camel/v1/common_types_support_test.go
  pkg/apis/camel/v1/maven_types.go
  pkg/apis/camel/v1/trait/builder.go
  pkg/apis/camel/v1/zz_generated.deepcopy.go
  pkg/builder/project.go
  pkg/client/camel/applyconfiguration/camel/v1/mavenbuildspec.go
  pkg/client/camel/applyconfiguration/camel/v1/mavenspec.go
  pkg/cmd/install.go
  pkg/trait/builder.go
  pkg/trait/builder_test.go
  pkg/util/maven/maven_project.go
  pkg/util/maven/maven_project_test.go
  pkg/util/maven/maven_types.go
  resources/traits.yaml
Labels: kind/feature
