Repository apache/camel-k, pull requests merged in 2023-05, with the labels that each got.

#4325 feat(cli): provide useful info in kubectl CLI
  addons/strimzi/duck/client/internalclientset/fake/register.go
  addons/strimzi/duck/client/internalclientset/scheme/register.go
  config/crd/bases/camel.apache.org_camelcatalogs.yaml
  config/crd/bases/camel.apache.org_integrationkits.yaml
  config/crd/bases/camel.apache.org_integrationplatforms.yaml
  config/crd/bases/camel.apache.org_integrations.yaml
  helm/camel-k/crds/crd-camel-catalog.yaml
  helm/camel-k/crds/crd-integration-kit.yaml
  helm/camel-k/crds/crd-integration-platform.yaml
  helm/camel-k/crds/crd-integration.yaml
  pkg/apis/camel/v1/camelcatalog_types.go
  pkg/apis/camel/v1/integration_types.go
  pkg/apis/camel/v1/integrationkit_types.go
  pkg/apis/camel/v1/integrationplatform_types.go
  pkg/client/camel/clientset/versioned/fake/register.go
  pkg/client/camel/clientset/versioned/scheme/register.go
Labels: kind/feature

#4329 fix(ci): native test path
  script/Makefile
Labels: kind/bug, trigger native test

#4344 fix(#4336): Restrict Knative binding provider execution
  pkg/util/bindings/knative_ref.go
  pkg/util/bindings/knative_ref_test.go
Labels: kind/bug

#4362 fix(cmd): promote should load catalog from k8s
  pkg/cmd/promote.go
Labels: kind/bug

#4367 chore(deps): ignore only k8s dependencies
  .github/dependabot.yml
Labels: dependencies

#4366 chore(deps): remove camelcase dependency
  .github/dependabot.yml
  go.mod
  go.sum
  pkg/cmd/version.go
  pkg/cmd/version_test.go
Labels: dependencies

#4378 chore(deps): golang.org/x/net upgrade
  pkg/apis/camel/go.mod
  pkg/apis/camel/go.sum
  pkg/client/camel/go.mod
  pkg/client/camel/go.sum
  pkg/kamelet/repository/go.mod
  pkg/kamelet/repository/go.sum
Labels: dependencies

#4416 feat(ci): publish arm64 architecture
  script/Makefile
Labels: kind/feature

#4427 chore(deps): remove old replacements
  go.mod
  go.sum
Labels: dependencies

#4428 chore(deps): remove deps and unused CLIs
  cmd/manager/main.go
  cmd/util/doc-gen/generators/generators.go
  cmd/util/doc-gen/generators/traitdocgen.go
  cmd/util/doc-gen/generators/traitmetadatagen.go
  cmd/util/doc-gen/main.go
  cmd/util/json-schema-gen/main.go
  cmd/util/license-check/main.go
  cmd/util/platform-check/main.go
  cmd/util/vfs-gen/main.go
  cmd/util/vfs-gen/multifs/multidir.go
  go.mod
  go.sum
  pkg/resources/resources_support.go
Labels: dependencies
