Repository apache/camel-k, pull requests merged in 2024-05, with the labels that each got.

#5096 feat(trait): enable health trait by default
  e2e/common/cli/get_test.go
  e2e/common/misc/files/cron-fallback.yaml
  e2e/common/misc/files/cron-quartz.yaml
  e2e/common/misc/files/cron-timer.yaml
  e2e/common/misc/files/cron-trait-yaml.yaml
  e2e/common/misc/files/cron-yaml.yaml
  e2e/common/misc/integration_fail_test.go
  e2e/common/traits/health_test.go
  e2e/common/traits/master_test.go
  pkg/apis/camel/v1/trait/health.go
  pkg/cmd/debug.go
  pkg/cmd/debug_test.go
  pkg/trait/health.go
  pkg/trait/health_test.go
  pkg/trait/jvm.go
  pkg/trait/trait_test.go
Labels: kind/feature

#5448 feat(api): show integration readiness
  helm/camel-k/crds/crd-integration.yaml
  pkg/apis/camel/v1/integration_types.go
  pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
Labels: kind/feature

#5457 fix(kamelets): parse the url used to download kamelet
  pkg/kamelet/repository/github_repository.go
  pkg/kamelet/repository/github_repository_test.go
Labels: kind/bug

#5478 fix(maven): move check for MAVEN_CMD before maven wrapper setup
  pkg/platform/platform.go
  pkg/util/maven/maven_command.go
Labels: trigger native test

#5499 feat(lint): enabe goconst linter
  .golangci.yml
  addons/telemetry/telemetry.go
  addons/telemetry/telemetry_test.go
  addons/vault/aws/aws_secrets_manager_test.go
  addons/vault/gcp/gcp_secret_manager_test.go
  e2e/advanced/main_test.go
  e2e/common/cli/main_test.go
  e2e/common/main_test.go
  e2e/common/traits/health_test.go
  e2e/support/test_support.go
  pkg/builder/project_test.go
  pkg/builder/quarkus.go
  pkg/builder/quarkus_test.go
  pkg/cmd/bind.go
  pkg/controller/integrationplatform/catalog_test.go
  pkg/install/common.go
  pkg/install/operator.go
  pkg/trait/builder.go
  pkg/trait/camel_test.go
  pkg/trait/istio.go
  pkg/trait/istio_test.go
  pkg/trait/jolokia_test.go
  pkg/trait/jvm.go
  pkg/trait/kamelets.go
  pkg/trait/kamelets_support.go
  pkg/trait/knative.go
  pkg/trait/knative_service.go
  pkg/trait/knative_service_test.go
  pkg/trait/knative_test.go
  pkg/trait/logging.go
  pkg/trait/logging_test.go
  pkg/trait/mount.go
  pkg/trait/openapi.go
  pkg/trait/platform.go
  pkg/trait/platform_test.go
  pkg/trait/quarkus.go
  pkg/trait/quarkus_test.go
  pkg/trait/route_test.go
  pkg/trait/service_binding.go
  pkg/trait/service_binding_test.go
  pkg/trait/trait_configure_test.go
  pkg/trait/trait_test.go
  pkg/trait/trait_types.go
  pkg/util/boolean/boolean.go
  pkg/util/camel/camel_runtime_test.go
  pkg/util/source/inspector_xml.go
Labels: trigger native test

#5504 [Release 2.3.x] fix(e2e): don't rollout Pods on operator upgrade
  e2e/install/upgrade/cli_upgrade_test.go
  e2e/install/upgrade/olm_upgrade_test.go
  e2e/support/test_support.go
  pkg/trait/environment.go
Labels: kind/bug

#5551 chore(ci): Knative 1.14.0
  .github/actions/kamel-install-knative/install-knative.sh
Labels: dependencies

#5561 fix(ctrl): synthetic Integration cannot set blockOwnerDeletion
  pkg/controller/synthetic/synthetic.go
  pkg/controller/synthetic/synthetic_test.go
Labels: kind/bug

#5555 fix(builder): add root and base image to S2I report
  docs/modules/ROOT/partials/apis/camel-k-crds.adoc
  helm/camel-k/crds/crd-build.yaml
  pkg/apis/camel/v1/build_types.go
  pkg/apis/camel/v1/zz_generated.deepcopy.go
  pkg/builder/builder_test.go
  pkg/builder/jib.go
  pkg/builder/s2i.go
  pkg/builder/spectrum.go
  pkg/builder/util.go
  pkg/client/camel/applyconfiguration/camel/v1/s2itask.go
  pkg/resources/config/crd/bases/camel.apache.org_builds.yaml
  pkg/trait/builder.go
  pkg/trait/builder_test.go
Labels: trigger native test

#5556 [Release 2.3.x] fix(builder): add root and base image to S2I report
  docs/modules/ROOT/partials/apis/camel-k-crds.adoc
  helm/camel-k/crds/crd-build.yaml
  pkg/apis/camel/v1/build_types.go
  pkg/apis/camel/v1/zz_generated.deepcopy.go
  pkg/builder/builder_test.go
  pkg/builder/jib.go
  pkg/builder/s2i.go
  pkg/builder/spectrum.go
  pkg/builder/util.go
  pkg/client/camel/applyconfiguration/camel/v1/s2itask.go
  pkg/resources/config/crd/bases/camel.apache.org_builds.yaml
  pkg/trait/builder.go
  pkg/trait/builder_test.go
Labels: trigger native test

#5568 fix(cmd): promote correct labels
  e2e/advanced/operator_id_filtering_test.go
  e2e/install/cli/global_test.go
  pkg/cmd/promote.go
  pkg/cmd/promote_test.go
  pkg/util/kubernetes/camel.go
Labels: kind/bug
